# Файл docker-compose должен начинаться с тега версии.
version: "3"

# Раздел, в котором будут описаны сервисы, начинается с 'services'.
services:

  # Назвать его можно так, как нужно разработчику.
  # Понятное название сервиса помогает определить его роль.
  # Здесь мы, для именования соответствующего сервиса, используем ключевое слово 'server'.
  server_part5:

    # Ключевое слово "build" позволяет задать
    # путь к файлу Dockerfile, который нужно использовать для создания образа,
    # который позволит запустить сервис.
    # Здесь './part5/' соответствует пути к папке сервера,
    # которая содержит соответствующий Dockerfile.
    build: ./part5/
      # контейнер будет автоматически перезапущен всегда, если он остановится или выйдет из состояния работы.
      # Это полезно, когда требуется обеспечить непрерывную работу контейнера, чтобы он не останавливался при возможных сбоях.
    restart: always

  proxy:
    build: ./part6/

    ports:
      - 80:8080
    restart: always
